sudo: false

language: d

d:
  - dmd-2.069.1
  - dmd-2.068.2
  - dmd-2.067.1
  - ldc-0.16.0
  # - gdc-4.9.2

install:
  - wget -q -O - "http://bit.ly/Doveralls" | bash
  - chmod +x doveralls

script:
  - dub test -b unittest-cov --compiler=${DC}
  - ./doveralls
